language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
before_install:
  - cpanm -n Devel::Cover::Report::Coveralls Test::CheckManifest
script:
  - export RELEASE_TESTING=1
  - perl Build.PL && ./Build build && cover -test -report coveralls
